# Generated by Django 2.2.1 on 2019-09-16 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='start day for shift')),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('switch', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accept', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cycle', models.PositiveSmallIntegerField(help_text='how many days is the shift pattern cycle', verbose_name=django.core.validators.MaxValueValidator(10))),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField(help_text='enter format hh:mm:ss')),
                ('shift_duration', models.DurationField(help_text='enter format hh:mm:ss')),
                ('shift_name', models.CharField(max_length=20)),
            ],
        ),
    ]
