# Generated by Django 2.2.1 on 2019-10-24 19:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='start day for shift')),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('switch', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accept', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False)),
                ('manager_responded', models.BooleanField(default=False)),
                ('manager_accept', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=20)),
                ('cycle', models.PositiveSmallIntegerField(help_text='how many days is the shift pattern cycle', validators=[django.core.validators.MaxValueValidator(10)], verbose_name='cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField(help_text='enter format hh:mm:ss')),
                ('shift_duration', models.DurationField(help_text='enter format hh:mm:ss')),
                ('shift_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SwapResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.BooleanField(default=False)),
                ('shift_start', models.DateTimeField()),
                ('json_data', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Day Off')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Employee')),
            ],
        ),
    ]
