# Generated by Django 2.2.1 on 2019-09-12 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cycle',
            field=models.PositiveSmallIntegerField(default=3, verbose_name=django.core.validators.MaxValueValidator(10)),
            preserve_default=False,
        ),
    ]
