# Generated by Django 2.2.1 on 2019-09-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_auto_20190916_1238'),
        ('user', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Group'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_schedule_1', to='schedule.Shift'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_schedule_2', to='schedule.Shift'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_schedule_3', to='schedule.Shift'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Group'),
        ),
        migrations.AddField(
            model_name='request',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='people.Individual'),
        ),
        migrations.AddField(
            model_name='request',
            name='applicant_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester_shift', to='schedule.Assign'),
        ),
        migrations.AddField(
            model_name='request',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='people.Individual'),
        ),
        migrations.AddField(
            model_name='request',
            name='receiver_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_shift', to='schedule.Assign'),
        ),
        migrations.AddField(
            model_name='assign',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Group'),
        ),
        migrations.AddField(
            model_name='assign',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Individual'),
        ),
    ]
