# Generated by Django 2.2.1 on 2019-09-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190916_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='individual',
            new_name='employee',
        ),
    ]
