# Generated by Django 2.2.1 on 2019-09-12 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='cycle',
            field=models.PositiveSmallIntegerField(help_text='how many days is the shift pattern cycle', verbose_name=django.core.validators.MaxValueValidator(10)),
        ),
    ]
