# Generated by Django 2.2.1 on 2019-10-09 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_employee_date_joined'),
        ('schedule', '0002_auto_20190919_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.BooleanField(default=False)),
                ('json_data', models.TextField()),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Employee')),
            ],
        ),
    ]
