# Generated by Django 2.2.1 on 2019-10-09 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_swapresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 10, 9, 22, 55, 42, 250909, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
