# Generated by Django 2.2.1 on 2019-10-09 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_swapresult_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapresult',
            name='shift_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
