# Generated by Django 2.2.1 on 2019-10-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_swapresult_shift_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='done',
            new_name='responded',
        ),
    ]
