# Generated by Django 2.2.1 on 2019-10-14 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0006_auto_20191010_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='manager_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='manager_responded',
            field=models.BooleanField(default=False),
        ),
    ]
