# Generated by Django 2.2.1 on 2019-10-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20191014_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='manager_accept',
        ),
        migrations.RemoveField(
            model_name='request',
            name='manager_responded',
        ),
    ]
