# Generated by Django 2.2.1 on 2019-10-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20191014_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='manager_responded',
            field=models.BooleanField(default=False),
        ),
    ]
