# Generated by Django 2.2.1 on 2019-10-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_request_manager_responded'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='manager_accept',
            field=models.BooleanField(default=False),
        ),
    ]
