# Generated by Django 2.2.1 on 2019-10-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_swap', models.BooleanField(default=False)),
                ('date_joined', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('name', models.CharField(max_length=5)),
                ('day', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
