# Generated by Django 2.2.1 on 2019-09-17 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Group'),
        ),
        migrations.AddField(
            model_name='position',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Group'),
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Group'),
        ),
        migrations.AddField(
            model_name='employee',
            name='person_position',
            field=models.ForeignKey(help_text='select a position', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='person_unit',
            field=models.ForeignKey(help_text='select a unit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Unit'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
