# Generated by Django 2.2.1 on 2019-09-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_individual_person_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='person',
            new_name='user',
        ),
    ]
