# Generated by Django 2.2.1 on 2019-09-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190919_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='weekday',
            field=models.ManyToManyField(blank=True, help_text='availability', to='people.Weekday'),
        ),
    ]
