# Generated by Django 2.2.1 on 2019-09-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190920_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weekday',
            new_name='Workday',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='weekday',
            new_name='workday',
        ),
    ]
