# Generated by Django 2.2.1 on 2019-09-12 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190911_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='employee_id',
            field=models.IntegerField(help_text='enter unique employee id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
