# Generated by Django 2.2.1 on 2019-10-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=5)),
                ('province', models.CharField(blank=True, max_length=5)),
                ('state', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RecentActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveSmallIntegerField()),
                ('object_name', models.TextField(max_length=200)),
                ('object_class', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacationNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('schedule_conflict', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
