# Generated by Django 2.2.1 on 2019-09-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_specific', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='organization',
            name='province',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
