# Generated by Django 2.2.1 on 2019-10-08 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_employee_date_joined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_specific', '0002_auto_20190924_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Employee')),
            ],
        ),
    ]
