# Generated by Django 2.2.1 on 2019-10-14 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_specific', '0004_vacationnotification_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacationnotification',
            old_name='rejected',
            new_name='responded',
        ),
    ]
