# Generated by Django 2.2.1 on 2019-10-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_specific', '0005_auto_20191014_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationnotification',
            name='schedule_conflict',
            field=models.BooleanField(default=False),
        ),
    ]
