# Generated by Django 2.2.1 on 2019-10-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191029_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='approve_all_swaps',
            field=models.BooleanField(default=False),
        ),
    ]
